# Generated by Django 2.2.4 on 2020-04-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Kollege',
        ),
    ]
