# Generated by Django 2.2.4 on 2020-04-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('postalcode', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('events', models.ManyToManyField(to='core.Event')),
                ('kollegen', models.ManyToManyField(to='core.Kollege')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
