# Generated by Django 2.2.4 on 2020-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
