# Generated by Django 2.2.4 on 2020-04-18 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200418_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='registerdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 20, 27, 24, 923943, tzinfo=utc)),
        ),
    ]
